(cl:in-package cepton_ros-msg)
(cl:export '(HEADER-VAL
          HEADER
          HANDLE-VAL
          HANDLE
          SERIAL_NUMBER-VAL
          SERIAL_NUMBER
          MODEL_NAME-VAL
          MODEL_NAME
          MODEL-VAL
          MODEL
          FIRMWARE_VERSION-VAL
          FIRMWARE_VERSION
          LAST_REPORTED_TEMPERATURE-VAL
          LAST_REPORTED_TEMPERATURE
          LAST_REPORTED_HUMIDITY-VAL
          LAST_REPORTED_HUMIDITY
          LAST_REPORTED_AGE-VAL
          LAST_REPORTED_AGE
          MEASUREMENT_PERIOD-VAL
          MEASUREMENT_PERIOD
          PTP_TS-VAL
          PTP_TS
          GPS_TS_YEAR-VAL
          GPS_TS_YEAR
          GPS_TS_MONTH-VAL
          GPS_TS_MONTH
          GPS_TS_DAY-VAL
          GPS_TS_DAY
          GPS_TS_HOUR-VAL
          GPS_TS_HOUR
          GPS_TS_MIN-VAL
          GPS_TS_MIN
          GPS_TS_SEC-VAL
          GPS_TS_SEC
          RETURN_COUNT-VAL
          RETURN_COUNT
          SEGMENT_COUNT-VAL
          SEGMENT_COUNT
          IS_MOCKED-VAL
          IS_MOCKED
          IS_PPS_CONNECTED-VAL
          IS_PPS_CONNECTED
          IS_NMEA_CONNECTED-VAL
          IS_NMEA_CONNECTED
          IS_PTP_CONNECTED-VAL
          IS_PTP_CONNECTED
          IS_CALIBRATED-VAL
          IS_CALIBRATED
          IS_OVER_HEATED-VAL
          IS_OVER_HEATED
          CEPTON_SDK_VERSION-VAL
          CEPTON_SDK_VERSION
          DATA-VAL
          DATA
))